### ISSUE TITLE
冒昧问下更新后设置key的地方在哪里？

### ISSUE THREAD

**Issue by aprpure** [chatgpt-web-dev/chatgpt-web#529]
我从v2.16.0版本更新以后，发现找不到设置key的地方了
如图所示（之前的是在最右边的那一栏，现在找不到了）：
![image](https://github.com/chatgpt-web-dev/chatgpt-web/assets/35722236/d2023d31-e7e7-4b33-894b-05de218c9fea)
我的docker-compose.yml

```
version: '3'

services:
  app:
    image: chatgptweb/chatgpt-web
    #image: aprpure/chatgpt-web
    container_name: chatgptweb
    restart: unless-stopped
    ports:
      - 3002:3002
    depends_on:
      - database
    environment:
      TZ: Asia/Shanghai
      # 访问jwt加密参数，可选 不为空则允许登录 同时需要设置 MONGODB_URL
      AUTH_SECRET_KEY: 
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 0
      # 网站名称
      SITE_TITLE: ChatGPT Web
      # mongodb 的连接字符串
      MONGODB_URL: "mongodb://xxx:xxxxxxx@database:27017"
      # 网站是否开启注册
      REGISTER_ENABLED: true
      # 开启注册之后 密码加密的盐
      PASSWORD_MD5_SALT: xxxxxxx
      # 开启注册之后 超级管理邮箱
      ROOT_USER: xxxxx@gmail.com
      REGISTER_ENABLED: true
      # 更多配置, 在运行后, 注册管理员, 在管理员页面中设置
    links:
      - database

  database:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: xxx
      MONGO_INITDB_ROOT_PASSWORD: xxxxxx
      MONGO_INITDB_DATABASE: chatgpt
```
