### ISSUE TITLE
没有使用反代依然没有打字机效果

### ISSUE THREAD

**Issue by fonlan** [chatgpt-web-dev/chatgpt-web#554]
在阿里云服务器上用docker compose部署了一台，compose配置如下。没有使用nginx反代，直接通过阿里云服务器的IP地址加端口3002访问。可以正常问答，但就是前端没有打字机效果，这可能有哪些原因？
```yml
version: '3'

services:
  app:
    image: chatgptweb/chatgpt-web:v2.18.0
    container_name: chatgptweb
    restart: unless-stopped
    ports:
      - 3002:3002
    depends_on:
      - database
    environment:
      TZ: Asia/Shanghai
      MAX_REQUEST_PER_HOUR: 0
      AUTH_SECRET_KEY: xxx
      SITE_TITLE: Chatgpt Web
      MONGODB_URL: 'mongodb://chatgpt:xxxxxxxx@database:27017'
      PASSWORD_MD5_SALT: xxx
      ROOT_USER: xxx@xxx.com
      REGISTER_ENABLED: true
    links:
      - database

  database:
    image: mongo
    container_name: chatgptweb-database
    restart: unless-stopped
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatgpt
      MONGO_INITDB_ROOT_PASSWORD: xxxxxxxx
      MONGO_INITDB_DATABASE: chatgpt

volumes:
  mongodb: {}
```
